version: 0.2

environment_variables:
  plaintext:
    TZ: "Asia/Seoul"

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - ./build.sh
  post_build:
    commands:
      - ./deploy.sh
